@startuml
start
:Игрок выбирает плитку для установки/удаления флага;
if (На плитке уже установлен флаг?) then (да)
    :Убрать флаг с плитки;
     
else (нет)
  :Установить флаг на плитку;
endif
:Продолжение игры;
stop
@enduml

