@startuml
start
:Игрок выбирает начать игру;
if (Размер поля выбран?) then (да)
    if (Выбранный размер доступен?) then (да)
      :Перейти к открытию плитки;
    else (нет)
      :Вернуться к началу игры;
      stop
endif
    
else (нет)
    :Начать игру со стандартными параметрами;
endif
@enduml 
