@startuml
start
:Игрок выбирает плитку для открытия;
:Проверить наличие мины на плитке;
if (Плитка содержит мину?) then (да)
  :Поражение;
else (нет)
  :Открыть плитку;
  :Отобразить соседние плитки;
  if (Все плитки без бомб открыты ?) then (да)
    :Победа;
    stop
  else
    :Продолжение игры ;
  endif
endif

@enduml