@startuml
skinparam packageStyle rect
actor Игрок as Player

rectangle "Главное меню" {
    Player --> (Начать)
    Player --> (Выбор параметров)
    Player --> (Выход)
}

rectangle "Игровое Поле" {
    (Начать) --> (Открыть плитку)
    (Начать) --> (Установить флаг)
  (Открыть плитку) --> (Продолжение игры)
  (Установить флаг) --> (Продолжение игры)   
}

rectangle "Результат"{
  (Открыть плитку) --> (Поражение)
  (Открыть плитку) --> (Победа)
  (Победа) -->(Новая игра)
  (Победа) -->(Выход из игры)
  (Поражение) -->(Новая игра)
  (Поражение) -->(Выход из игры)
}

rectangle "Настройки" {
    (Выбор параметров) --> (Выбор размера поля)
    (Выбор параметров) --> (Выбор количества бомб)
}
@enduml   
